language: "haskell"
install:
  - "travis_retry cabal install 'cpphs >= 1.18.3'"
  - "cabal install --dry-run -v3"
  - "travis_retry cabal install --force-reinstalls"
script: "scripts/travis-test"
notifications:
  irc:
    channels: "irc.freenode.net#fay"
    skip_join: true
  email:
    recipients:
      - adam@bergmark.nl
    on_success: change
    on_failure: change
